function [Tprime, Tprime_old2,  Tprime_old,...
          DIVprime, DIVprime_old2, DIVprime_old, ...
          CURLprime, CURLprime_old2, CURLprime_old] = ...
    func_robert_filter(Tprime, Tprime_old2,  Tprime_old, ...
                       DIVprime, DIVprime_old2,  DIVprime_old, ...
                       CURLprime, CURLprime_old2,  CURLprime_old)

Globals_var;


[Tprime_old ] = ...
    func_robert_filter_s( Tprime,Tprime_old2,Tprime_old );

[DIVprime_old ] = ...
    func_robert_filter_s( DIVprime,DIVprime_old2,DIVprime_old );

[CURLprime_old ] = ...
    func_robert_filter_s( CURLprime,CURLprime_old2,CURLprime_old );
